=== lpoliakova/WebDataBase/TableConfig.dtd
<!ELEMENT table (name, attributes, entries)>

        <!ELEMENT attributes (attribute*)>
        <!ELEMENT attribute (name, type)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT type (#PCDATA)>

        <!ELEMENT entries (entry*)>
        <!ELEMENT entry (field)+>
        <!ELEMENT field (name, type, value)>
        <!ELEMENT value (#PCDATA)>

=== lpoliakova/WebDataBase/DATABASE/people/Managers.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE table SYSTEM "TableConfig.dtd">
<table>
<name>Managers</name>
<attributes>
<attribute>
<name>Salary</name>
<type>REAL</type>
</attribute>
<attribute>
<name>Age</name>
<type>INT</type>
</attribute>
<attribute>
<name>Name</name>
<type>CHAR</type>
</attribute>
</attributes>
<entries>
<entry>
<field>
<name>Salary</name>
<type>REAL</type>
<value>1000.0</value>
</field>
<field>
<name>Age</name>
<type>INT</type>
<value>45</value>
</field>
<field>
<name>Name</name>
<type>CHAR</type>
<value>Leonard</value>
</field>
</entry>
<entry>
<field>
<name>Salary</name>
<type>REAL</type>
<value>1500.0</value>
</field>
<field>
<name>Age</name>
<type>INT</type>
<value>55</value>
</field>
<field>
<name>Name</name>
<type>CHAR</type>
<value>Samanta</value>
</field>
</entry>
</entries>
</table>

=== lpoliakova/WebDataBase/DATABASE/people/Stuff.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE table SYSTEM "TableConfig.dtd">
<table>
<name>Stuff</name>
<attributes>
<attribute>
<name>Age</name>
<type>INT</type>
</attribute>
<attribute>
<name>Name</name>
<type>CHAR</type>
</attribute>
</attributes>
<entries>
<entry>
<field>
<name>Age</name>
<type>INT</type>
<value>21</value>
</field>
<field>
<name>Name</name>
<type>CHAR</type>
<value>Jim</value>
</field>
</entry>
<entry>
<field>
<name>Age</name>
<type>INT</type>
<value>25</value>
</field>
<field>
<name>Name</name>
<type>CHAR</type>
<value>Kerry</value>
</field>
</entry>
</entries>
</table>
